<?php
/**
 * @file
 * sfova_recent_events.features.menu_links.inc
 */

/**
 * Implements hook_menu_default_menu_links().
 */
function sfova_recent_events_menu_default_menu_links() {
  $menu_links = array();

  // Exported menu link: main-menu:recent-events/all
  $menu_links['main-menu:recent-events/all'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'recent-events/all',
    'router_path' => 'recent-events',
    'link_title' => 'Recent Activities',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
  );
  // Translatables
  // Included for use with string extractors like potx.
  t('Recent Activities');


  return $menu_links;
}
